site_name: My Docs
site_url: https://WncFht.github.io/notes/

plugins:
  - search
  - bi_directional_links
      # debug: true  # 启用调试模式

nav:
  - Home: index.md
  - index2: subdir/index.md
  - page1: page1.md
  - page2: subdir/page2.md
  - page4: dir2/page4.md